name: Check Generated Tests In Sync

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
    paths:
      - "test_generator/**"
      - "test_templates/**"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  check_generated_tests:
    name: Check generated tests in sync
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          submodules: true

      - name: Setup Node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020
        with:
          node-version: 24.x
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Check generated tests in sync
        run: bin/check-generated-tests-in-sync
