# This workflow will verify the exercises in the repository.
#
# Requires scripts:
# - bin/verify-exercises

name: Test

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  verify_exercises:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332

      - name: Setup Node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
        with:
          node-version: 24.x
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Verify all exercises
        run: bin/verify-exercises
